Ot101 38 pagina inicio
alkemyTech/OT101-CLIENT pull request #20
Opened 2021-12-07 21:11 UTC by alejandropascuale

**Summary**

- Render ImageSlider component in Home page
- Add dynamic message if the user is logged in
- Request the last 4 news to dynamic rendering

**Evidence**
![image](https://user-images.githubusercontent.com/83843450/145106674-34ef3458-e19d-48ce-abb5-35556ac2809e.png)

2021-12-07 23:20 UTC, FranciscoMessina commented on src/components/Home.js
> +    const [state, setstate] = useState([]);
Creo que lo mejor seria darle al state un nombre significativo, y también al nombrar [state, setState] la función que lo setea es con camelCase.

2021-12-07 23:23 UTC, FranciscoMessina commented on src/pages/Home.js
> +    .then(response => setNews(response.reverse().slice(0, 3)));
No entiendo muy bien el proposito de el reverse y el slice, como viene la informacion para que sea necesario hacer eso?

2021-12-07 23:24 UTC, FranciscoMessina approved these changes
Esta bien, deje algunos comentarios sobre algunas dudas que tenia y cosas que cambiaria un poquito.

2021-12-07 23:26 UTC, alejandropascuale commented on src/components/Home.js
> +    const [state, setstate] = useState([]);
Este componente quedó demás me parece, porque el archivo en el que trabajé está en la carpeta pages. Podriamos eliminarlo.

2021-12-07 23:27 UTC, alejandropascuale commented on src/pages/Home.js
> +    .then(response => setNews(response.reverse().slice(0, 3)));
El ticket solicita mostrar las ultimas 4 novedades. Del array de datos, uso reverse() para darlo vuelta y slice, para tomar los primeros 4 (serian en realidad los ultimos 4 porque lo di vuelta antes).

2021-12-08 00:03 UTC, mateo-14 requested changes
Habría que cambiar eso que te puse, si no, no te mostraría nada
También quedaron archivos que no corresponden al ticket

2021-12-08 00:03 UTC, mateo-14 commented on src/pages/Home.js
> +      <h1>{user.isLoggin === true? `Hola ${user.firstName}, bienvenido a Fundación somos más`: 'Bienvenido a Fundación somos más'}</h1>
- Cambiar user.isLoggin por user.isLogged
- La propiedad firstName, está en user.data, así que quedaría user.data.firstName

2021-12-08 00:11 UTC, alejandropascuale commented on src/pages/Home.js
> +      <h1>{user.isLoggin === true? `Hola ${user.firstName}, bienvenido a Fundación somos más`: 'Bienvenido a Fundación somos más'}</h1>
Hechos los cambios. Gracias!

2021-12-08 00:23 UTC, mateo-14 approved these changes

2021-12-12 14:32 UTC, FranciscoMessina commented on src/pages/Home.js
> +    .then(response => setNews(response.reverse().slice(0, 3)));
Ah, okey, eso creo que igual lo optimo seria manejarlo desde el backend, dando la posibilidad de al mandar el request pedir un sort order y un limit de noticias, ya que si solo vas a usar cuatro estas mandando mas información que no es necesaria sin propósito.

2021-12-21 10:09 UTC, merged