move sweet alert service to services folder
alkemyTech/OT101-CLIENT pull request #24
Opened 2021-12-09 14:56 UTC by alejandropascuale

**Summary**

- Move Sweet Alert service from hooks to services folder
- Add to Sweet Alert services two parameters (title and message) to use in any situation or component

**Evidence**
![image](https://user-images.githubusercontent.com/83843450/145419644-47168226-d1b9-44b0-b359-2ac2e5b06a94.png)

2021-12-09 15:38 UTC, pabloameni reviewed
Ale, veo positivo que ya no sea un hook porque no dejaba usarlo en promesas. Faltaría que se pueda utilizar para confirmar acciones, ej:
Swal.fire({
  title: 'Do you want to save the changes?',
  showCancelButton: true,
}).then((result) => {
  if (result.isConfirmed) {
    Swal.fire('Saved!', '', 'success')
  } else {
    Swal.fire('Canceled!', '', 'info')
  }
})

2021-12-09 15:59 UTC, alejandropascuale commented
> 

Ok, agrego nuevo metodo para realizar una confirmación

2021-12-09 21:14 UTC, pabloameni reviewed
Perdón por explicarme mal Ale. El código que había pegado era un ejemplo de uso de confirmación en sweetalert2, no quise indicar que debías utilizar dicho código.
Creo que habría dos formas de implementarlo:
* callback que pase el `result` al llamante
* callbacks onConfirm y onCancel para llamar según resultado del `result` dentro del .then

2021-12-09 23:22 UTC, alejandropascuale commented
> Perdón por explicarme mal Ale. El código que había pegado era un ejemplo de uso de confirmación en sweetalert2, no quise indicar que debías utilizar dicho código. Creo que habría dos formas de implementarlo:
> 
> * callback que pase el `result` al llamante
> * callbacks onConfirm y onCancel para llamar según resultado del `result` dentro del .then

No hay problema. A mi tambien me parecio util la sugerencia porque no habia ninguna alerta de ese estilo, solamente estaban las basicas que sugeria el ticket que hice. A medida que sean necesarias las podemos ir agregando en el mismo servicio,

2021-12-09 23:52 UTC, mateo-14 requested changes
Yo sugiero que se retorne directamente un 
```js
MySwal.fire({title, message, icon: ..., showCancelButton: ...})
// icon y showCancelButton varían según el action enviado
```
Retornando esto directamente el que usa el servicio, si quisiera usar el action de tipo "confirm", puede usar la promesa retornada para saber el resultado.
Y si quisieras podrías comprobar antes de retornar si el **"action"** es valido (confirm, cancel o info)
También cambiaría el nombre, ya que no es más un hook.

2021-12-10 14:22 UTC, alejandropascuale commented
> Yo sugiero que se retorne directamente un
> 
> ```js
> MySwal.fire({title, message, icon: ..., showCancelButton: ...})
> // icon y showCancelButton varían según el action enviado
> ```
> 
> Retornando esto directamente el que usa el servicio, si quisiera usar el action de tipo "confirm", puede usar la promesa retornada para saber el resultado. Y si quisieras podrías comprobar antes de retornar si el **"action"** es valido (confirm, cancel o info) También cambiaría el nombre, ya que no es más un hook.

Probé como comentas, pero si no te entendí mal, en el componente en el que se quiera usar el servicio se va a tener que importar nuevamente sweet alert y usando una promesa, dar nuevamente feedback de confirmacion o no de la accion elegida.
Tambien se me ocurrió reducir código y dejarlo asi:
![image](https://user-images.githubusercontent.com/83843450/145588395-d455a5ec-219d-424f-85f5-954e3cf92897.png)

2021-12-10 21:07 UTC, mateo-14 commented
> 
> Probé como comentas, pero si no te entendí mal, en el componente en el que se quiera usar el servicio se va a tener que importar nuevamente sweet alert y usando una promesa, dar nuevamente feedback de confirmacion o no de la accion elegida. Tambien se me ocurrió reducir código y dejarlo asi: ![image](https://user-images.githubusercontent.com/83843450/145588395-d455a5ec-219d-424f-85f5-954e3cf92897.png)

Pero el feedback es necesario?
Yo había pensado usar el servicio de esta manera:
```js 

// Async await
const onClick = async () => {
    /* El tercer argumento sería uno de los action que te pedía el ticket ('confirm', 'info' y 'error')
       Y dependiendo de cual se haya usado mostrar un icono distinto y mostrar o no el "cancel button"
    */
    const result = await sweetAlertService('titulo', 'mensaje', 'confirm')
    if (result.isConfirmed) {
      //Acá podría mostrar otra alerta (usando el mismo servicio sweetAlertService) o lo que quisiera
    } 
}

// Promesas
const onClick = () => {
    sweetAlertService('titulo', 'mensaje', 'confirm')
    .then((result) => {
        if (result.isConfirmed) {
        //Acá podría mostrar otra alerta (usando el mismo servicio sweetAlertService) o lo que quisiera
        } 
    });  
}

```
Otra cosa, también estuve viendo para qué era el **withReactContent** y creo que se podría sacar, porque la única función que tiene es hacer que el contenido de la alerta pueda ser contenido react y no se está usando.

2021-12-20 11:08 UTC, alejandropascuale commented
@mateo-14 Estan hechos los cambios.

2021-12-20 15:17 UTC, hfoncea approved these changes

2021-12-20 15:17 UTC, merged