Ot101 34 backend frontend auth connect
alkemyTech/OT101-CLIENT pull request #29
Opened 2021-12-10 19:53 UTC by nicocagiao

2021-12-16 19:04 UTC, mateo-14 requested changes
Habría que hacer unos cambios y usar el action de redux para que la información del usuario quede guardada en el state global (redux store). Todo lo demás muy bien!

2021-12-16 19:04 UTC, mateo-14 commented on src/components/LoginForm.jsx
> +                    authService.login(values)
usar **dispatch(login(values))**
El "login()" es una **action** de redux que se importa desde 'features/user/userSlice.js '

2021-12-16 19:04 UTC, mateo-14 commented on src/pages/Register.js
> +      authService.register(values)
Esto está perfecto, aunque en un futuro se tiene que cambiar por un **dispatch(register(values))**, ya que ahora cuando un usuario se registra se logea automáticamente.
El "register()" es una **action** de redux que se importaría desde 'features/user/userSlice.js ' (Todavía no implementada)

2021-12-20 21:36 UTC, nicocagiao commented on src/components/LoginForm.jsx
> +                    authService.login(values)
Intenté aplicar el "dispatch(login(values))" pero no parece funcionar. No se si lo estoy aplicando mal o si habrá otro error.

2021-12-20 21:41 UTC, mateo-14 requested changes

2021-12-20 21:41 UTC, mateo-14 commented on src/components/LoginForm.jsx
> +import login from '../features/user/userSlice'
Acá deberia ser **"import { login } from '../features/user/userSlice'"**

2021-12-21 10:17 UTC, merged